"""init

Revision ID: 4a0a4cedfdc3
Revises: 
Create Date: 2026-09-28 09:58:19.389709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0a4cedfdc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_metric',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('portfolio', sa.String(), nullable=False),
    sa.Column('cagr', sa.Float(), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('sortino', sa.Float(), nullable=True),
    sa.Column('max_dd', sa.Float(), nullable=True),
    sa.Column('calmar', sa.Float(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('run_id', 'portfolio')
    )
    op.create_table('backtest_series',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('portfolio', sa.String(), nullable=False),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('ret', sa.Float(), nullable=True),
    sa.Column('drawdown', sa.Float(), nullable=True),
    sa.Column('rolling_sharpe', sa.Float(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('run_id', 'date', 'portfolio')
    )
    op.create_table('factors_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mkt', sa.Float(), nullable=True),
    sa.Column('smb', sa.Float(), nullable=True),
    sa.Column('hml', sa.Float(), nullable=True),
    sa.Column('rmw', sa.Float(), nullable=True),
    sa.Column('cma', sa.Float(), nullable=True),
    sa.Column('liq', sa.Float(), nullable=True),
    sa.Column('for_', sa.Float(), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index('idx_factors_daily_date', 'factors_daily', ['date'], unique=False)
    op.create_table('foreign_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('foreign_owned_pct', sa.Float(), nullable=True),
    sa.Column('room_total_pct', sa.Float(), nullable=True),
    sa.Column('room_remaining_pct', sa.Float(), nullable=True),
    sa.Column('net_foreign_buy_value', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'ticker')
    )
    op.create_table('frontier_point',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('ret', sa.Float(), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('is_tangency', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('run_id', 'idx')
    )
    op.create_table('fundamentals_quarterly',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('book_equity', sa.Numeric(), nullable=True),
    sa.Column('total_assets', sa.Numeric(), nullable=True),
    sa.Column('net_income', sa.Numeric(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'fiscal_year', 'quarter')
    )
    op.create_table('grs_result',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('universe', sa.String(), nullable=False),
    sa.Column('grs_stat', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('mean_abs_alpha', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('run_id', 'model', 'universe')
    )
    op.create_table('hypothesis_result',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('hypothesis', sa.String(), nullable=False),
    sa.Column('statistic', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id', 'hypothesis')
    )
    op.create_table('index_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('index_code', sa.String(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'index_code')
    )
    op.create_table('job',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('kff_factors_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mkt_rf', sa.Float(), nullable=True),
    sa.Column('smb', sa.Float(), nullable=True),
    sa.Column('hml', sa.Float(), nullable=True),
    sa.Column('rmw', sa.Float(), nullable=True),
    sa.Column('cma', sa.Float(), nullable=True),
    sa.Column('rf', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index('idx_kff_factors_daily_date', 'kff_factors_daily', ['date'], unique=False)
    op.create_table('portfolio_run',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('config_hash', sa.String(), nullable=True),
    sa.Column('best_model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('portfolio_weight',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('mu', sa.Float(), nullable=True),
    sa.Column('sigma', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('run_id', 'ticker')
    )
    op.create_table('price_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=True),
    sa.Column('high', sa.Numeric(), nullable=True),
    sa.Column('low', sa.Numeric(), nullable=True),
    sa.Column('close', sa.Numeric(), nullable=True),
    sa.Column('adj_close', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.BIGINT(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('shares_outstanding', sa.BIGINT(), nullable=True),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('ret', sa.Float(), nullable=True),
    sa.Column('excess_ret', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'ticker')
    )
    op.create_index('idx_price_daily_date_ticker', 'price_daily', ['date', 'ticker'], unique=False)
    op.create_table('regression_result',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('alpha_t', sa.Float(), nullable=True),
    sa.Column('alpha_p', sa.Float(), nullable=True),
    sa.Column('beta_mkt', sa.Float(), nullable=True),
    sa.Column('beta_mkt_t', sa.Float(), nullable=True),
    sa.Column('beta_mkt_p', sa.Float(), nullable=True),
    sa.Column('beta_smb', sa.Float(), nullable=True),
    sa.Column('beta_smb_t', sa.Float(), nullable=True),
    sa.Column('beta_smb_p', sa.Float(), nullable=True),
    sa.Column('beta_hml', sa.Float(), nullable=True),
    sa.Column('beta_hml_t', sa.Float(), nullable=True),
    sa.Column('beta_hml_p', sa.Float(), nullable=True),
    sa.Column('beta_rmw', sa.Float(), nullable=True),
    sa.Column('beta_rmw_t', sa.Float(), nullable=True),
    sa.Column('beta_rmw_p', sa.Float(), nullable=True),
    sa.Column('beta_cma', sa.Float(), nullable=True),
    sa.Column('beta_cma_t', sa.Float(), nullable=True),
    sa.Column('beta_cma_p', sa.Float(), nullable=True),
    sa.Column('beta_liq', sa.Float(), nullable=True),
    sa.Column('beta_liq_t', sa.Float(), nullable=True),
    sa.Column('beta_liq_p', sa.Float(), nullable=True),
    sa.Column('beta_for', sa.Float(), nullable=True),
    sa.Column('beta_for_t', sa.Float(), nullable=True),
    sa.Column('beta_for_p', sa.Float(), nullable=True),
    sa.Column('beta_vol', sa.Float(), nullable=True),
    sa.Column('beta_vol_t', sa.Float(), nullable=True),
    sa.Column('beta_vol_p', sa.Float(), nullable=True),
    sa.Column('r2', sa.Float(), nullable=True),
    sa.Column('adj_r2', sa.Float(), nullable=True),
    sa.Column('aic', sa.Float(), nullable=True),
    sa.Column('bic', sa.Float(), nullable=True),
    sa.Column('n_obs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('run_id', 'model', 'ticker')
    )
    op.create_table('risk_free',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rf_annual', sa.Float(), nullable=True),
    sa.Column('rf_daily', sa.Float(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('stock',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('vn30_constituent',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'start_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vn30_constituent')
    op.drop_table('stock')
    op.drop_table('risk_free')
    op.drop_table('regression_result')
    op.drop_index('idx_price_daily_date_ticker', table_name='price_daily')
    op.drop_table('price_daily')
    op.drop_table('portfolio_weight')
    op.drop_table('portfolio_run')
    op.drop_index('idx_kff_factors_daily_date', table_name='kff_factors_daily')
    op.drop_table('kff_factors_daily')
    op.drop_table('job')
    op.drop_table('index_daily')
    op.drop_table('hypothesis_result')
    op.drop_table('grs_result')
    op.drop_table('fundamentals_quarterly')
    op.drop_table('frontier_point')
    op.drop_table('foreign_daily')
    op.drop_index('idx_factors_daily_date', table_name='factors_daily')
    op.drop_table('factors_daily')
    op.drop_table('backtest_series')
    op.drop_table('backtest_metric')
    # ### end Alembic commands ###
